# Generated by Django 5.2.6 on 2026-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
